services:
  - type: worker
    name: rag-telegram-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
